# -*- coding: utf-8 -*-
"""parkee-Scripting data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9ScG2YPMhq3p4rYAbnUUHa2pXp7h8sa
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df_a = pd.read_csv("branch_a.csv", encoding='utf-8', skipinitialspace=True)
df_b = pd.read_csv("branch_b.csv", encoding='utf-8', skipinitialspace=True)
df_c = pd.read_csv("branch_c.csv", encoding='utf-8', skipinitialspace=True)

print (df_a)
print (df_b)
print (df_c)

df = pd.concat([df_a, df_b, df_c], ignore_index=True)
print(df)

df_cleaned = df.dropna(subset=["transaction_id", "date", "customer_id"]).copy()
print(df_cleaned)

df_cleaned["date"] = pd.to_datetime(df_cleaned["date"])
print (df_cleaned)

df_deduped = df_cleaned.sort_values("date", ascending=False).drop_duplicates(subset="transaction_id", keep="first")
print(df_deduped)

df_deduped["total"] = df_deduped["quantity"] * df_deduped["price"]
print(df_deduped)

result = df_deduped.groupby("branch")["total"].sum().reset_index()

result.to_csv("total_sales_per_branch.csv", index=False)
print(result)